title: Rafael Bayer
author:
  name: rafibayer
  email: rafibayer7+blog@gmail.com

# Short bio or description (displayed in the header)
description: Software Engineer II @ Microsoft Azure

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/26726001?v=4

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: solarized-dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    email: rafibayer7+blog@gmail.com
    github: rafibayer
    linkedin: rafael-bayer

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md

# Build settings
theme: minima

plugins:
  # - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  # - jekyll-redirect-from
  - jekyll-seo-tag

kramdown:
  # section headers get corresponding ID's, allows internal links
  auto_ids: true
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME